# Form implementation generated from reading ui file 'VentanaSeleccionColumnas.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutSuperior = QtWidgets.QHBoxLayout()
        self.layoutSuperior.setObjectName("layoutSuperior")
        self.btnInsertarArchivo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsertarArchivo.setMinimumSize(QtCore.QSize(150, 40))
        self.btnInsertarArchivo.setObjectName("btnInsertarArchivo")
        self.layoutSuperior.addWidget(self.btnInsertarArchivo)
        self.lineEditRutaArchivo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditRutaArchivo.setReadOnly(True)
        self.lineEditRutaArchivo.setObjectName("lineEditRutaArchivo")
        self.layoutSuperior.addWidget(self.lineEditRutaArchivo)
        self.verticalLayout.addLayout(self.layoutSuperior)
        self.tableViewDataFrame = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableViewDataFrame.setMinimumSize(QtCore.QSize(0, 300))
        self.tableViewDataFrame.setAlternatingRowColors(True)
        self.tableViewDataFrame.setObjectName("tableViewDataFrame")
        self.verticalLayout.addWidget(self.tableViewDataFrame)
        self.layoutBotones = QtWidgets.QHBoxLayout()
        self.layoutBotones.setObjectName("layoutBotones")
        self.btnSeleccionarColumnas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSeleccionarColumnas.setMinimumSize(QtCore.QSize(200, 40))
        self.btnSeleccionarColumnas.setVisible(True)
        self.btnSeleccionarColumnas.setObjectName("btnSeleccionarColumnas")
        self.layoutBotones.addWidget(self.btnSeleccionarColumnas)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutBotones.addItem(spacerItem)
        self.cmbOpcionesPreprocesado = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbOpcionesPreprocesado.setMinimumSize(QtCore.QSize(300, 35))
        self.cmbOpcionesPreprocesado.setVisible(True)
        self.cmbOpcionesPreprocesado.setObjectName("cmbOpcionesPreprocesado")
        self.layoutBotones.addWidget(self.cmbOpcionesPreprocesado)
        self.verticalLayout.addLayout(self.layoutBotones)
        self.layoutInferior = QtWidgets.QHBoxLayout()
        self.layoutInferior.setObjectName("layoutInferior")
        self.btnDividirDatos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDividirDatos.setMinimumSize(QtCore.QSize(200, 40))
        self.btnDividirDatos.setVisible(True)
        self.btnDividirDatos.setObjectName("btnDividirDatos")
        self.layoutInferior.addWidget(self.btnDividirDatos)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutInferior.addItem(spacerItem1)
        self.btnPasarSiguientePestana = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPasarSiguientePestana.setMinimumSize(QtCore.QSize(250, 40))
        self.btnPasarSiguientePestana.setVisible(True)
        self.btnPasarSiguientePestana.setStyleSheet("background-color: #4CAF50; color: white; font-size: 11pt;")
        self.btnPasarSiguientePestana.setObjectName("btnPasarSiguientePestana")
        self.layoutInferior.addWidget(self.btnPasarSiguientePestana)
        self.verticalLayout.addLayout(self.layoutInferior)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Selección de Columnas y Preprocesado"))
        self.btnInsertarArchivo.setText(_translate("MainWindow", "Insertar archivo"))
        self.lineEditRutaArchivo.setPlaceholderText(_translate("MainWindow", "Falta la ruta"))
        self.btnSeleccionarColumnas.setText(_translate("MainWindow", " seleccionar columnas"))
        self.btnDividirDatos.setText(_translate("MainWindow", " dividir datos en (Test/No Test)"))
        self.btnPasarSiguientePestana.setText(_translate("MainWindow", "Pasar a otra pestaña"))
