# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmbEntrada = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbEntrada.setGeometry(QtCore.QRect(70, 110, 241, 31))
        self.cmbEntrada.setObjectName("cmbEntrada")
        self.cmbSalida = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbSalida.setGeometry(QtCore.QRect(480, 110, 241, 31))
        self.cmbSalida.setObjectName("cmbSalida")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 50, 141, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 50, 161, 41))
        self.label_2.setMaximumSize(QtCore.QSize(161, 16777215))
        self.label_2.setObjectName("label_2")
        self.btnConfirmar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConfirmar.setGeometry(QtCore.QRect(70, 190, 141, 28))
        self.btnConfirmar.setObjectName("btnConfirmar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Entrada</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Salida</span></p></body></html>"))
        self.btnConfirmar.setText(_translate("MainWindow", "Confirmar Seleccion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
