# Form implementation generated from reading ui file 'VentanaCargaUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 449)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.FrameContenedor = QtWidgets.QFrame(parent=self.centralwidget)
        self.FrameContenedor.setMinimumSize(QtCore.QSize(300, 150))
        self.FrameContenedor.setMaximumSize(QtCore.QSize(600, 300))
        self.FrameContenedor.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FrameContenedor.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FrameContenedor.setObjectName("FrameContenedor")
        self.gridLayout = QtWidgets.QGridLayout(self.FrameContenedor)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.LhLblEntradaSalida = QtWidgets.QHBoxLayout()
        self.LhLblEntradaSalida.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.LhLblEntradaSalida.setContentsMargins(0, 0, 0, 0)
        self.LhLblEntradaSalida.setSpacing(7)
        self.LhLblEntradaSalida.setObjectName("LhLblEntradaSalida")
        self.lblEntrada = QtWidgets.QLabel(parent=self.FrameContenedor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEntrada.sizePolicy().hasHeightForWidth())
        self.lblEntrada.setSizePolicy(sizePolicy)
        self.lblEntrada.setMaximumSize(QtCore.QSize(500, 40))
        self.lblEntrada.setObjectName("lblEntrada")
        self.LhLblEntradaSalida.addWidget(self.lblEntrada)
        self.lblSalida = QtWidgets.QLabel(parent=self.FrameContenedor)
        self.lblSalida.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSalida.sizePolicy().hasHeightForWidth())
        self.lblSalida.setSizePolicy(sizePolicy)
        self.lblSalida.setMinimumSize(QtCore.QSize(0, 0))
        self.lblSalida.setMaximumSize(QtCore.QSize(500, 40))
        self.lblSalida.setObjectName("lblSalida")
        self.LhLblEntradaSalida.addWidget(self.lblSalida)
        self.verticalLayout_2.addLayout(self.LhLblEntradaSalida)
        self.HlCmbEntradaSalida = QtWidgets.QHBoxLayout()
        self.HlCmbEntradaSalida.setObjectName("HlCmbEntradaSalida")
        self.cmbEntrada = QtWidgets.QComboBox(parent=self.FrameContenedor)
        self.cmbEntrada.setObjectName("cmbEntrada")
        self.HlCmbEntradaSalida.addWidget(self.cmbEntrada)
        self.cmbSalida = QtWidgets.QComboBox(parent=self.FrameContenedor)
        self.cmbSalida.setObjectName("cmbSalida")
        self.HlCmbEntradaSalida.addWidget(self.cmbSalida)
        self.verticalLayout_2.addLayout(self.HlCmbEntradaSalida)
        self.btnConfirmar = QtWidgets.QPushButton(parent=self.FrameContenedor)
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.verticalLayout_2.addWidget(self.btnConfirmar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.FrameContenedor, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblEntrada.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Entrada</span></p></body></html>"))
        self.lblSalida.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Salida</span></p></body></html>"))
        self.btnConfirmar.setText(_translate("MainWindow", "Confirmar Seleccion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
